version: '0.0'
services:
  database:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: bot
    environment:
        TOKEN: $TOKEN

        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOSTNAME: $POSTGRES_HOSTNAME
        POSTGRES_PORT: $POSTGRES_PORT

        TEMAIKENS_CHANNEL_ID: $TEMAIKENS_CHANNEL_ID
    depends_on:
      - database