version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always

  bot:
    build: .
    container_name: bot
    environment:
        TOKEN: $TOKEN

        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_HOSTNAME: $POSTGRES_HOSTNAME
        POSTGRES_PORT: $POSTGRES_PORT

        TEMAIKENS_CHANNEL_ID: $TEMAIKENS_CHANNEL_ID
    depends_on:
      - postgres
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
